### PR TITLE
Listen also to IPv6 socket

### PR DESCRIPTION
**Pull request by StephenKing**

### CODE REVIEW

**Comment by mrimann** [comment]
Ping me if you need one to test it.

**Comment by fabarea** [comment]
Got it on my radar. However I am not sure the actual server will properly works with IPv6. Last time we tried, it kind of stuck (nginx didn't restart or something like that). Solution: we need a fresh install, current one is pretty outdated... I asked people from ther server team what is our way to set up a new VM, things are unclear for me.

**Comment by StephenKing** [comment]
Well, we solved this for all other installations ;-)

I once more updated my repo and will merge this PR now.

I noticed that srv154 became a snowflake and `site-cheftypo3org` was removed from the run list. So I edited it on the server as well.

**Comment by mrimann** [comment]
Thanks guys!

**Comment by fabarea** [comment]
One thing, please don't run the `chef-client`, otherwise it will mess up the demo server because of dependency to MySQL. I think you did a manual change when you said "I edited it on the server as well." That's good.

**Comment by StephenKing** [comment]
Sorry, I meant the role `site-demotypo3org` has been removed from the run list (was already).

Therefore, only the base software is managed by chef. Please ask next time, when you struggle.

**Comment by fabarea** [comment]
Fine like that. I wasn't sure anymore what was in the run list or not. Thanks for double-checking.

**Pull request merged**
